### ISSUE TITLE
Can't run 0x-launch-kit locally on Windows 

### ISSUE THREAD

**Issue by hichamsatoual** [0xProject/0x-launch-kit#9]
I deployed 0x-launch-kit locally on docker in windows OS , after I run this command : npx @0x/launch-kit-wizard && docker-compose up  Then When I open http://localhost:3001/   I show nginx result 403 Forbidden, I am also deployed  0x-launch-kit to Digitalocean droplet docker I showed the same error, Other thing when I browse to   /usr/share/nginx/html directory inside nginx container I didn't show index.html please can you solve problem ?

**Comment by dekz** [comment]
@malisting the first build takes some time before it will be available. This is discussed in #5. We're working on a "Building in progress" page so it is obvious to the user. 0xproject/0x-launch-kit-frontend#518

**Comment by malisting** [comment]
it shows me this error
frontend_1  | The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
frontend_1  | error Command failed with exit code 1.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root_frontend_1 exited with code 1

**Comment by dekz** [comment]
@malisting how much memory is available on the machine?

**Comment by malisting** [comment]
1GB

**Comment by malisting** [comment]
I use digitalocean docker droplet with 1BG

**Comment by dekz** [comment]
Minimum memory requirements are 4gb.

**Comment by sagarrbhatt** [comment]
I am trying to use the 0x launch-kit. Whenever I try to run- "npx @0x/launch-kit-wizard && docker-compose up"

I get this - 

At line:1 char:27
+ npx @0x/launch-kit-wizard && docker-compose up
+                           ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
